twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
      - .forms/security/authentication_form.widget.html.twig
      - .forms/security/registration_form.widget.html.twig

when@test:
    twig:
        strict_variables: true
