controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

quizz_controllers:
    resource: ../../src/Controller/Quizz
    type: annotation
    prefix: /quizz
