version: '3.0'
services:
    database:
        ports:
            - ${PORT_DATABASE}:3306

    php:
        ports:
            - ${PORT_PHP}:9000

    httpd:
        ports:
            - ${PORT_HTTPD}:80

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - ${PORT_PHPMYADMIN}:80

    smtp:
        image: djfarrelly/maildev:0.13.4
        ports:
            - ${PORT_MAILDEV}:80
